/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BeliRouteImport } from './routes/beli'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAgenRouteImport } from './routes/admin/agen'
import { Route as AdminKonfirmasiRouteImport } from './routes/admin/konfirmasi'
import { Route as AdminPenggunaRouteImport } from './routes/admin/pengguna'
import { Route as AdminTiketboxRouteImport } from './routes/admin/tiketbox'
import { Route as AdminTiketingRouteImport } from './routes/admin/tiketing'
import { Route as BayarOrderIdRouteImport } from './routes/bayar.$orderId'
import { Route as TiketOrderIdRouteImport } from './routes/tiket.$orderId'
import { Route as UploadOrderIdRouteImport } from './routes/upload.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BeliRoute = BeliRouteImport.update({
  id: '/beli',
  path: '/beli',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgenRoute = AdminAgenRouteImport.update({
  id: '/agen',
  path: '/agen',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKonfirmasiRoute = AdminKonfirmasiRouteImport.update({
  id: '/konfirmasi',
  path: '/konfirmasi',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPenggunaRoute = AdminPenggunaRouteImport.update({
  id: '/pengguna',
  path: '/pengguna',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTiketboxRoute = AdminTiketboxRouteImport.update({
  id: '/tiketbox',
  path: '/tiketbox',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTiketingRoute = AdminTiketingRouteImport.update({
  id: '/tiketing',
  path: '/tiketing',
  getParentRoute: () => AdminRoute,
} as any)
const BayarOrderIdRoute = BayarOrderIdRouteImport.update({
  id: '/bayar/$orderId',
  path: '/bayar/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const TiketOrderIdRoute = TiketOrderIdRouteImport.update({
  id: '/tiket/$orderId',
  path: '/tiket/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadOrderIdRoute = UploadOrderIdRouteImport.update({
  id: '/upload/$orderId',
  path: '/upload/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/beli': typeof BeliRoute
  '/login': typeof LoginRoute
  '/admin/agen': typeof AdminAgenRoute
  '/admin/konfirmasi': typeof AdminKonfirmasiRoute
  '/admin/pengguna': typeof AdminPenggunaRoute
  '/admin/tiketbox': typeof AdminTiketboxRoute
  '/admin/tiketing': typeof AdminTiketingRoute
  '/bayar/$orderId': typeof BayarOrderIdRoute
  '/tiket/$orderId': typeof TiketOrderIdRoute
  '/upload/$orderId': typeof UploadOrderIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beli': typeof BeliRoute
  '/login': typeof LoginRoute
  '/admin/agen': typeof AdminAgenRoute
  '/admin/konfirmasi': typeof AdminKonfirmasiRoute
  '/admin/pengguna': typeof AdminPenggunaRoute
  '/admin/tiketbox': typeof AdminTiketboxRoute
  '/admin/tiketing': typeof AdminTiketingRoute
  '/bayar/$orderId': typeof BayarOrderIdRoute
  '/tiket/$orderId': typeof TiketOrderIdRoute
  '/upload/$orderId': typeof UploadOrderIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/beli': typeof BeliRoute
  '/login': typeof LoginRoute
  '/admin/agen': typeof AdminAgenRoute
  '/admin/konfirmasi': typeof AdminKonfirmasiRoute
  '/admin/pengguna': typeof AdminPenggunaRoute
  '/admin/tiketbox': typeof AdminTiketboxRoute
  '/admin/tiketing': typeof AdminTiketingRoute
  '/bayar/$orderId': typeof BayarOrderIdRoute
  '/tiket/$orderId': typeof TiketOrderIdRoute
  '/upload/$orderId': typeof UploadOrderIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/beli'
    | '/login'
    | '/admin/agen'
    | '/admin/konfirmasi'
    | '/admin/pengguna'
    | '/admin/tiketbox'
    | '/admin/tiketing'
    | '/bayar/$orderId'
    | '/tiket/$orderId'
    | '/upload/$orderId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beli'
    | '/login'
    | '/admin/agen'
    | '/admin/konfirmasi'
    | '/admin/pengguna'
    | '/admin/tiketbox'
    | '/admin/tiketing'
    | '/bayar/$orderId'
    | '/tiket/$orderId'
    | '/upload/$orderId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/beli'
    | '/login'
    | '/admin/agen'
    | '/admin/konfirmasi'
    | '/admin/pengguna'
    | '/admin/tiketbox'
    | '/admin/tiketing'
    | '/bayar/$orderId'
    | '/tiket/$orderId'
    | '/upload/$orderId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BeliRoute: typeof BeliRoute
  LoginRoute: typeof LoginRoute
  BayarOrderIdRoute: typeof BayarOrderIdRoute
  TiketOrderIdRoute: typeof TiketOrderIdRoute
  UploadOrderIdRoute: typeof UploadOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beli': {
      id: '/beli'
      path: '/beli'
      fullPath: '/beli'
      preLoaderRoute: typeof BeliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agen': {
      id: '/admin/agen'
      path: '/agen'
      fullPath: '/admin/agen'
      preLoaderRoute: typeof AdminAgenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/konfirmasi': {
      id: '/admin/konfirmasi'
      path: '/konfirmasi'
      fullPath: '/admin/konfirmasi'
      preLoaderRoute: typeof AdminKonfirmasiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pengguna': {
      id: '/admin/pengguna'
      path: '/pengguna'
      fullPath: '/admin/pengguna'
      preLoaderRoute: typeof AdminPenggunaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tiketbox': {
      id: '/admin/tiketbox'
      path: '/tiketbox'
      fullPath: '/admin/tiketbox'
      preLoaderRoute: typeof AdminTiketboxRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tiketing': {
      id: '/admin/tiketing'
      path: '/tiketing'
      fullPath: '/admin/tiketing'
      preLoaderRoute: typeof AdminTiketingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/bayar/$orderId': {
      id: '/bayar/$orderId'
      path: '/bayar/$orderId'
      fullPath: '/bayar/$orderId'
      preLoaderRoute: typeof BayarOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiket/$orderId': {
      id: '/tiket/$orderId'
      path: '/tiket/$orderId'
      fullPath: '/tiket/$orderId'
      preLoaderRoute: typeof TiketOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload/$orderId': {
      id: '/upload/$orderId'
      path: '/upload/$orderId'
      fullPath: '/upload/$orderId'
      preLoaderRoute: typeof UploadOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAgenRoute: typeof AdminAgenRoute
  AdminKonfirmasiRoute: typeof AdminKonfirmasiRoute
  AdminPenggunaRoute: typeof AdminPenggunaRoute
  AdminTiketboxRoute: typeof AdminTiketboxRoute
  AdminTiketingRoute: typeof AdminTiketingRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgenRoute: AdminAgenRoute,
  AdminKonfirmasiRoute: AdminKonfirmasiRoute,
  AdminPenggunaRoute: AdminPenggunaRoute,
  AdminTiketboxRoute: AdminTiketboxRoute,
  AdminTiketingRoute: AdminTiketingRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BeliRoute: BeliRoute,
  LoginRoute: LoginRoute,
  BayarOrderIdRoute: BayarOrderIdRoute,
  TiketOrderIdRoute: TiketOrderIdRoute,
  UploadOrderIdRoute: UploadOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
